name: "Second custom action"
description: "My second custom action trail"

inputs:
  myinput:
    description: "My custom input"
    required: true
  non-mandatory-input:
    description: "This is a non mandatory input"
    default: "Sukumaran"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: "Displaying OS config..."
      shell: bash
      run: uname -a

    - name: "Displaying the ip config..."
      shell: bash
      run: ifconfig

    - name: "Displaying the input content..."
      shell: bash
      run: |
        echo ${{ inputs.myinput }}
        echo ${{ inputs.non-mandatory-input }}
