name: Github Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
    - name: Echo message
      run: echo "Hello, friend. Hello, friend?"

  second-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repository...
      uses: actions/checkout@v2

    - name: Displaying the contents....
      run: pwd; ls -l; uname -a; whoami

    - name: Displaying ip configurations...
      run: ifconfig 

  thirds-job:
    runs-on: ubuntu-latest 
    needs: second-job

    steps:
    - name: Checking out the repository...
      uses: actions/checkout@v2

    - name: Displaying current directory...
      run: pwd; ls -l

  foruth-job:
    uses: ./.github/workflows/test.yml

  fifth-job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checking out the repo...
        uses: actions/checkout@v3

      - name: Listing the content...
        run: pwd; ls -l
        
      - name: My first custom action1 
        uses: ./.github/actions/action1

      - name: My second custom action2
        uses: ./.github/actions/action2
        with:
          myinput: "Minato Namikaze"
          non-mandatory-input: "Minato"
